// Code generated by "stringer -type=Type"; DO NOT EDIT.

package jsonb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Null-0]
	_ = x[True-1]
	_ = x[False-2]
	_ = x[Int-3]
	_ = x[Int5-4]
	_ = x[Float-5]
	_ = x[Float5-6]
	_ = x[Text-7]
	_ = x[TextJ-8]
	_ = x[Text5-9]
	_ = x[TextRaw-10]
	_ = x[Array-11]
	_ = x[Object-12]
	_ = x[Reserved13-13]
	_ = x[Reserved14-14]
	_ = x[Reserved15-15]
}

const _Type_name = "NullTrueFalseIntInt5FloatFloat5TextTextJText5TextRawArrayObjectReserved13Reserved14Reserved15"

var _Type_index = [...]uint8{0, 4, 8, 13, 16, 20, 25, 31, 35, 40, 45, 52, 57, 63, 73, 83, 93}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
