name: test-sqlite

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: With sqlite_enable_tmstmpvfs
      run: go test -v -tags sqlite_enable_tmstmpvfs
      
    - name: Race
      run: go test -v -race ./...
    - name: Race with sqlite_trunk, sqlite_enable_api_armor and sqlite_enable_tmstmpvfs
      run: go test -v -race -tags sqlite_trunk,sqlite_enable_api_armor,sqlite_enable_tmstmpvfs

    - name: No CGO build
      run: CGO_ENABLED=0 go install ./...
